language: python
before_install:
- sudo add-apt-repository --yes ppa:fontforge/fontforge
- sudo add-apt-repository -y ppa:chris-lea/node.js
- sudo add-apt-repository -y ppa:hash3g/ots
- sudo apt-get update -qq
- sudo apt-get install python-fontforge ttfautohint nodejs swig otsanitizer
- cp /usr/lib/python2.7/dist-packages/fontforge.* "$HOME/virtualenv/python2.7.8/lib/python2.7/site-packages"
install:
- pip install git+https://github.com/behdad/fontTools.git
- pip install git+https://github.com/googlefonts/fontcrunch.git
- pip install git+https://github.com/googlefonts/fontbakery-cli.git
- pip install jinja2
before_script:
- mkdir -p builds/$TRAVIS_COMMIT
- npm install -g bower
script: (set -o pipefail; PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH fontbakery-build.py
  . 2>&1 | tee -a builds/$TRAVIS_COMMIT/buildlog.txt)
branches:
  only:
  - master
after_script:
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH fontbakery-report.py builds/$TRAVIS_COMMIT
- rm -rf builds/$TRAVIS_COMMIT/sources
- rm -rf builds/$TRAVIS_COMMIT/build.state.yaml
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH fontbakery-travis-deploy.py
env:
  global:
    secure: HTO7r6iIM+c2l+TPASIlokaIvUQm4ouF6jzK4uAOPdW7lua4OGXXbf/tdcxJUaLxoFmiwZmxfeISk9EVsIfJOj5JSY1Xtdki1czOlzcU2Hbo2SZFfx5UNd9O16W8dBEPAhYLHrTQa4Upv8aXwJehKfQA5Pnf+f+r8sbCjvyoYiE=
