language: python
before_install:
- sudo add-apt-repository --yes ppa:fontforge/fontforge
- sudo add-apt-repository -y ppa:chris-lea/node.js
- sudo apt-get update -qq
- sudo apt-get install python-fontforge ttfautohint nodejs
- cp /usr/lib/python2.7/dist-packages/fontforge.* "$HOME/virtualenv/python2.7.8/lib/python2.7/site-packages"
install:
- pip install git+https://github.com/behdad/fontTools.git
- pip install git+https://github.com/googlefonts/fontcrunch.git
- pip install git+https://github.com/googlefonts/fontbakery-cli.git
- pip install jinja2
before_script:
- mkdir -p $TRAVIS_COMMIT
- npm install -g bower
script: PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH fontbakery-build.py .
branches:
  only:
  - master
after_script:
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH fontbakery-report.py $TRAVIS_COMMIT
- rm -rf $TRAVIS_COMMIT/sources
- rm -rf $TRAVIS_COMMIT/build.state.yaml
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH fontbakery-travis-deploy.py
env:
  global:
    secure: Sk5Aa07SaTxW46n1Fpr/xXaS2EORSI3XuS5OxEMXFyO3prVdybe2rQlGdPNIszFzBk5wrICsvnGv6gpc8Tk3lTRPXxcM2Qmm7pkwsf7ZfFk1ApesVW2j4u9kws8yETabq2MGZzZr54wWgG/UYT0MLtCfSUoxvydsHtm8hxM8s+E=
